Fix getting latest github release version number
Reference: https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c#gistcomment-2649739

Full error message:

     > [4/16] RUN apt-get install -y curl grep sed dpkg &&     TINI_VERSION=`curl https://github.com/krallin/tini/releases/latest | grep -o "/v.*"" | sed 's:^..\(.*\).$:\1:'` &&     curl -L "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" > tini.deb &&     dpkg -i tini.deb &&     rm tini.deb &&     apt-get clean     && rm -rf /var/lib/apt/lists/*:
    # 13 10.49 Unpacking curl (7.58.0-2ubuntu3.24) ...
    # 13 11.16 Setting up libcurl4:amd64 (7.58.0-2ubuntu3.24) ...
    # 13 11.56 Setting up curl (7.58.0-2ubuntu3.24) ...
    # 13 11.96 Processing triggers for libc-bin (2.27-3ubuntu1.5) ...
    100     9    0     9    0     0     25      0 --:--:-- --:--:-- --:--:--    25
    # 13 13.38 dpkg-deb: error: 'tini.deb' is not a Debian format archive
    # 13 13.38 dpkg: error processing archive tini.deb (--install):
    # 13 13.38  dpkg-deb --control subprocess returned error exit status 2
    # 13 13.55 Errors were encountered while processing:
    # 13 13.55  tini.deb
    ------
    ERROR: failed to solve: process "/bin/bash -c apt-get install -y curl grep sed dpkg &&     TINI_VERSION=`curl https://github.com/krallin/tini/releases/latest | grep -o \"/v.*\\\"\" | sed 's:^..\\(.*\\).$:\\1:'` &&     curl -L \"https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb\" > tini.deb &&     dpkg -i tini.deb &&     rm tini.deb &&     apt-get clean     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 1

Note that an extra space is added after the pound symbol `#` in the error message to prevent github linking issues.