Remove google cloud-sdk
Full error message:

    # 16 2500.0 deb http://packages.cloud.google.com/apt cloud-sdk-focal main
    # 16 2500.1   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    # 16 2500.1                                  Dload  Upload   Total   Spent    Left  Speed
    100  2659  100  2659    0     0  15459      0 --:--:-- --:--:-- --:--:-- 15459
    # 16 2500.3 Warning: apt-key output should not be parsed (stdout is not a terminal)
    # 16 2501.0 OK
    # 16 2501.5 Ign:1 http://packages.cloud.google.com/apt cloud-sdk-focal InRelease
    # 16 2501.7 Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
    # 16 2501.7 Err:3 http://packages.cloud.google.com/apt cloud-sdk-focal Release
    # 16 2501.7   404  Not Found [IP: 172.217.160.78 80]
    # 16 2501.8 Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
    # 16 2502.1 Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
    # 16 2502.4 Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
    # 16 2502.6 Reading package lists...
    # 16 2503.3 E: The repository 'http://packages.cloud.google.com/apt cloud-sdk-focal Release' does not have a Release file.
    # 16 ERROR: process "/bin/bash -c apt-get update -y     && apt-get install -y --no-install-recommends         build-essential         curl         git         gnupg2         make         cmake         ffmpeg         swig         libz-dev         unzip         zlib1g-dev         libglfw3         libglfw3-dev         libxrandr2         libxinerama-dev         libxi6         libxcursor-dev         libgl1-mesa-dev         libgl1-mesa-glx         libglew-dev         libosmesa6-dev         lsb-release         ack-grep         patchelf         vim         emacs         wget         xpra         xserver-xorg-dev         xvfb     && export CLOUD_SDK_REPO=\"cloud-sdk-$(lsb_release -c -s)\"     && echo \"deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main\"             | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list     && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg             | apt-key add -     && apt-get update -y     && apt-get install -y google-cloud-sdk     && apt-get clean     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
    ------
     > [6/16] RUN apt-get update -y     && apt-get install -y --no-install-recommends         build-essential         curl         git         gnupg2         make         cmake         ffmpeg         swig         libz-dev         unzip         zlib1g-dev         libglfw3         libglfw3-dev         libxrandr2         libxinerama-dev         libxi6         libxcursor-dev         libgl1-mesa-dev         libgl1-mesa-glx         libglew-dev         libosmesa6-dev         lsb-release         ack-grep         patchelf         vim         emacs         wget         xpra         xserver-xorg-dev         xvfb     && export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"     && echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main"             | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list     && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg             | apt-key add -     && apt-get update -y     && apt-get install -y google-cloud-sdk     && apt-get clean     && rm -rf /var/lib/apt/lists/*:
    # 16 2501.0 OK
    # 16 2501.5 Ign:1 http://packages.cloud.google.com/apt cloud-sdk-focal InRelease
    # 16 2501.7 Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
    # 16 2501.7 Err:3 http://packages.cloud.google.com/apt cloud-sdk-focal Release
    # 16 2501.7   404  Not Found [IP: 172.217.160.78 80]
    # 16 2501.8 Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
    # 16 2502.1 Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
    # 16 2502.4 Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease

    # 16 2503.3 E: The repository 'http://packages.cloud.google.com/apt cloud-sdk-focal Release' does not have a Release file.
    ------
    ERROR: failed to solve: process "/bin/bash -c apt-get update -y     && apt-get install -y --no-install-recommends         build-essential         curl         git         gnupg2         make         cmake         ffmpeg         swig         libz-dev         unzip         zlib1g-dev         libglfw3         libglfw3-dev         libxrandr2         libxinerama-dev         libxi6         libxcursor-dev         libgl1-mesa-dev         libgl1-mesa-glx         libglew-dev         libosmesa6-dev         lsb-release         ack-grep         patchelf         vim         emacs         wget         xpra         xserver-xorg-dev         xvfb     && export CLOUD_SDK_REPO=\"cloud-sdk-$(lsb_release -c -s)\"     && echo \"deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main\"             | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list     && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg             | apt-key add -     && apt-get update -y     && apt-get install -y google-cloud-sdk     && apt-get clean     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

Note that an extra space is added after the pound symbol `#` in the error message to prevent github linking issues.