Add safe directory for GitPython
Reference: https://stackoverflow.com/a/76706837

Full error message:

    (softlearning) root@338939057e54:~/softlearning# softlearning run_example_local examples.development \
    >     --algorithm SAC \
    >     --universe gym \
    >     --domain HalfCheetah \
    >     --task v3 \
    >     --exp-name my-sac-experiment-1 \
    >     --checkpoint-frequency 1000  # Save the checkpoint to resume training later
    2023-11-29 09:30:27.840788: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /root/.mujoco/mujoco200_linux/bin:/root/.mujoco/mujoco200/bin:/root/.mujoco/mjpro150/bin::/usr/lib/nvidia-000
    2023-11-29 09:30:27.840808: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
    Compiling /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/cymj.pyx because it depends on /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/pxd/mujoco.pxd.
    [1/1] Cythonizing /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/cymj.pyx
    running build_ext
    building 'mujoco_py.cymj' extension
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning/lib
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning/lib/python3.8
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning/lib/python3.8/site-packages
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/gl
    gcc -pthread -B /opt/conda/envs/softlearning/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py -I/root/.mujoco/mujoco200/include -I/opt/conda/envs/softlearning/lib/python3.8/site-packages/numpy/core/include -I/opt/conda/envs/softlearning/include/python3.8 -c /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/cymj.c -o /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/cymj.o -fopenmp -w
    gcc -pthread -B /opt/conda/envs/softlearning/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py -I/root/.mujoco/mujoco200/include -I/opt/conda/envs/softlearning/lib/python3.8/site-packages/numpy/core/include -I/opt/conda/envs/softlearning/include/python3.8 -c /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/gl/osmesashim.c -o /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/gl/osmesashim.o -fopenmp -w
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/lib.linux-x86_64-cpython-38
    creating /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/lib.linux-x86_64-cpython-38/mujoco_py
    gcc -pthread -shared -B /opt/conda/envs/softlearning/compiler_compat -L/opt/conda/envs/softlearning/lib -Wl,-rpath=/opt/conda/envs/softlearning/lib -Wl,--no-as-needed -Wl,--sysroot=/ /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/cymj.o /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-38/opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/gl/osmesashim.o -L/root/.mujoco/mujoco200/bin -Wl,--enable-new-dtags,-R/root/.mujoco/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /opt/conda/envs/softlearning/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_38_linuxcpuextensionbuilder/lib.linux-x86_64-cpython-38/mujoco_py/cymj.cpython-38-x86_64-linux-gnu.so -fopenmp
    INFO:absl:MUJOCO_GL is not set, so an OpenGL backend will be chosen automatically.
    INFO:absl:Successfully imported OpenGL backend: glfw
    INFO:absl:MuJoCo library version is: 200
    Warning: robosuite package not found. Run `pip install robosuite` to use robosuite environments.
    Traceback (most recent call last):
      File "/opt/conda/envs/softlearning/bin/softlearning", line 33, in <module>
        sys.exit(load_entry_point('softlearning', 'console_scripts', 'softlearning')())
      File "/root/softlearning/softlearning/scripts/console_scripts.py", line 207, in main
        return cli()
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/root/softlearning/softlearning/scripts/console_scripts.py", line 73, in run_example_local_cmd
        return run_example_local(example_module_name, example_argv)
      File "/root/softlearning/examples/instrument.py", line 225, in run_example_local
        variant_spec = example_module.get_variant_spec(example_args)
      File "/root/softlearning/examples/development/__init__.py", line 16, in get_variant_spec
        variant_spec = get_variant_spec(command_line_args, *args, **kwargs)
      File "/root/softlearning/examples/development/variants.py", line 570, in get_variant_spec
        variant_spec = get_variant_spec_image(
      File "/root/softlearning/examples/development/variants.py", line 526, in get_variant_spec_image
        variant_spec = get_variant_spec_base(
      File "/root/softlearning/examples/development/variants.py", line 434, in get_variant_spec_base
        'git_sha': get_git_rev(__file__),
      File "/root/softlearning/softlearning/utils/git.py", line 20, in get_git_rev
        git_rev = repo.active_branch.commit.name_rev
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/git/refs/symbolic.py", line 197, in _get_commit
        obj = self._get_object()
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/git/refs/symbolic.py", line 190, in _get_object
        return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/git/objects/base.py", line 64, in new_from_sha
        oinfo = repo.odb.info(sha1)
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/git/db.py", line 37, in info
        hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/git/cmd.py", line 1068, in get_object_header
        return self.__get_object_header(cmd, ref)
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/git/cmd.py", line 1057, in __get_object_header
        return self._parse_object_header(cmd.stdout.readline())
      File "/opt/conda/envs/softlearning/lib/python3.8/site-packages/git/cmd.py", line 1019, in _parse_object_header
        raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
    ValueError: SHA could not be resolved, git returned: b''